Task #2(Components)_Added component of product
NikiforovJacob/junior-course-boilerplate pull request #1
Opened 2019-08-09 16:41 UTC by NikiforovJacob

2019-08-10 18:01 UTC, CSSSR-School requested changes
Есть замечания, которые нужно поправить

2019-08-10 18:01 UTC, CSSSR-School commented on src/Components/ProductsItems/ProductsItems.js
> +    width: '700px',
Стили нужно оставить в стилевых файлах. Просто эти файлы должны лежать рядом с js файлом компонента

2019-08-10 18:01 UTC, CSSSR-School commented on src/index.js
> +        <ProductsH title={'Список товаров'}/>
Строки можно передавать без фигурных скобок:
```jsx
<ProductsH title='Список товаров' />
```

2019-08-10 18:01 UTC, CSSSR-School commented on src/Components/ProductsH/ProductsH.js
> +const ProductsH = props => {
Советую дать компоненту более абстрактное имя, не привязанное к продукту, т.е. `Title` или `Heading`. Возможно позже он нам еще понадобится

2019-08-11 09:00 UTC, NikiforovJacob commented on src/index.js
> +        <ProductsH title={'Список товаров'}/>
Ага, поправил.

2019-08-11 09:01 UTC, NikiforovJacob commented on src/Components/ProductsH/ProductsH.js
> +const ProductsH = props => {
Спасибо, поправил.

2019-08-11 09:06 UTC, NikiforovJacob commented on src/Components/ProductsItems/ProductsItems.js
> +    width: '700px',
Поправил. В задании вроде бы нету такого требования, а из теории понял, что общепринятого решения по стилизации компонентов нет и можно выбирать на свое усмотрение. Возможно, стоит добавить требование в задание?

2019-08-11 16:51 UTC, CSSSR-School commented on src/Components/ProductsItems/ProductsItems.js
> +    width: '700px',
Подумаем над добавлением уточнения, спасибо!

2019-08-11 16:52 UTC, CSSSR-School commented
@NikiforovJacob все хорошо. Можно вливать в master

2019-08-12 13:04 UTC, merged